name: Docker Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Clean up old images
        run: |
          docker image prune -f
          
      - name: Build Docker Image
        run: |
          echo "Starting build process... gas mih"
          docker info
          docker build -t ${{ github.event.repository.name }}:latest .
          docker images
          
      - name: Deploy Container
        run: |
          echo "Starting deployment process..."
          docker container ls
          docker container stop ${{ github.event.repository.name }} || true
          docker container rm ${{ github.event.repository.name }} || true
          docker run -d --name ${{ github.event.repository.name }} \
            -p 4001:3000 \
            --restart unless-stopped \
            ${{ github.event.repository.name }}:latest
          docker container ls